language: generic
sudo: false

env:
    global:
    - BYOND_MAJOR="508"
    - BYOND_MINOR="1287"
    matrix:
    - DM_MAPFILE="metastation"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - chmod +x ./install-byond.sh && ./install-byond.sh

script:
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh -M${DM_MAPFILE} tgstation.dme